from jukebox.lyricdict import custom
offset = 81 # Offset in seconds

def metas_with(total_length):
	return([dict(artist = "Tame Impala",
                  genre = "Psychedelic Rock",
                  lyrics = custom['ytv_full'],
                  total_length=total_length,
                  offset=offset,
                  ),
             dict(artist = "Hilltop Hoods",
                  genre = "Hip Hop",
                  lyrics = custom['ytv_full'],
                  total_length=total_length,
                  offset=offset,
                  ),
             dict(artist = "Australian Crawl",
                  genre = "Rock",
                  lyrics = custom['ytv_full'],
                  total_length=total_length,
                  offset=offset,
                  ),
             dict(artist = "Ganggajang",
                  genre = "Rock",
                  lyrics = custom['ytv_full'],
                  total_length=total_length,
                  offset=offset,
                  ),
             dict(artist = "Savage Garden",
                  genre = "Pop",
                  lyrics = custom['ytv_full'],
                  total_length=total_length,
                  offset=offset,
                  ),
             dict(artist = "Cold Chisel",
                  genre = "Rock",
                  lyrics = custom['ytv_full'],
                  total_length=total_length,
                  offset=offset,
                  ),
             dict(artist = "Tina Arena",
                  genre = "Pop",
                  lyrics = custom['ytv_full'],
                  total_length=total_length,
                  offset=offset,
                  ),
             dict(artist = "The Presets",
                  genre = "Indietronica",
                  lyrics = custom['ytv_full'],
                  total_length=total_length,
                  offset=offset,
                  ),
             dict(artist = "Kylie Minogue",
                  genre = "Dance Pop",
                  lyrics = custom['ytv_full'],
                  total_length=total_length,
                  offset=offset,
                  ),
             dict(artist = "Olivia Newton-John",
                  genre = "Dance Pop",
                  lyrics = custom['ytv_full'],
                  total_length=total_length,
                  offset=offset,
                  ),
             dict(artist = "The Birthday Party",
                  genre = "Post-Punk",
                  lyrics = custom['ytv_full'],
                  total_length=total_length,
                  offset=offset,
                  ),
             ])