from jukebox.lyricdict import custom

def metas_with(total_length, offset):
	return([dict(artist = "John Farnham",
                  genre = "Rock",
                  lyrics = custom['ytv_full'],
                  total_length=total_length,
                  offset=offset,
                  ),
             dict(artist = "John Farnham",
                  genre = "Rock",
                  lyrics = custom['ytv_full'],
                  total_length=total_length,
                  offset=offset,
                  ),
             dict(artist = "John Farnham",
                  genre = "Rock",
                  lyrics = custom['ytv_full'],
                  total_length=total_length,
                  offset=offset,
                  ),
             dict(artist = "John Farnham",
                  genre = "Rock",
                  lyrics = custom['ytv_full'],
                  total_length=total_length,
                  offset=offset,
                  ),
             dict(artist = "John Farnham",
                  genre = "Rock",
                  lyrics = custom['ytv_full'],
                  total_length=total_length,
                  offset=offset,
                  ),
             ])